### ISSUE TITLE
'streams_sines' throwing "SCRIPT ERROR: missing Streams" on fates v.200106

### ISSUE THREAD

**Issue by tildebyte** [nathankoch/streams#1]
Trying to run streams_sines on fates v.200106 and getting

```lua
norns.script.load("code/streams/streams_sines.lua")
# script load: /home/we/dust/code/streams/streams_sines.lua
# cleanup
# script clear
including /home/we/dust/code/streams/lib/streams.lua
including /home/we/dust/code/streams/lib/stream_pool.lua
including /home/we/dust/code/streams/lib/stream.lua
including /home/we/dust/code/streams/lib/modulators.lua
including /home/we/dust/code/arcify/lib/arcify.lua
including /home/we/dust/code/billboard/lib/billboard.lua
pset >> write: /home/we/dust/data/system.pset
# script run
loading engine: Streams
### SCRIPT ERROR: missing Streams
<ok>
```

I've poked around here and there, but I really don't understand why I'm seeing this. Compared to e.g. awake, streams_sines seems to be using engine.name the same way ¯\_(ツ)_/¯

**Comment by mimetaur** [comment]
Hmm - interesting.

The first thing to do is reboot your Norns/Fates if you haven’t already, new engines (and Streams has two) always cause errors.

Next, I’ll experiment with Streams on the latest Norns OS - I haven’t used it since May (it hasn’t gotten an “official” release - it was part of my MFA thesis in 2019) so there might be something that rolled out at an OS level that broke. I’ll update my Norns and pull down my latest copy of Streams and see how it goes.

**Comment by tildebyte** [comment]
Thanks! I forgot about needing to refresh... I 'm currently facing a different issue, but as soon as I'm back up and running I'll try again.

**Comment by tildebyte** [comment]
DERP. Yeah, now that I've fixed my *other* issue (which required rebooting anyway), everything's fine.

**Comment by mimetaur** [comment]
Awesome! I’ll be rolling out an official release on Lines soon too, hopefully with a few more features.
